In [1]:
from urllib.request import urlopen
from io import BytesIO
from zipfile import ZipFile


def download_and_unzip(url, extract_to='.'):
    http_response = urlopen(url)
    zipfile = ZipFile(BytesIO(http_response.read()))
    zipfile.extractall(path=extract_to)


download_and_unzip("https://files.grouplens.org/datasets/movielens/ml-100k.zip",
                   extract_to='.')

Next, let's import all of the modules that we'll use in this notebook.

In [2]:
# Standard library imports
import random
import time

# Third-party imports
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', None)

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from tqdm.notebook import tqdm
from sklearn import preprocessing as pp
from sklearn.model_selection import train_test_split
import scipy.sparse as sp

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
def make_dfs():
  columns_name=['user_id','item_id','rating','timestamp']
  train_df = pd.read_csv("./ml-100k/ua.base",sep="\t",names=columns_name)
  test_df = pd.read_csv("./ml-100k/ua.test",sep="\t",names=columns_name)

  # df = df[df['rating']>=3]

  # train, test = train_test_split(df.values, test_size=0.1, random_state=16)
  # train_df = pd.DataFrame(train, columns=df.columns)
  # test_df = pd.DataFrame(test, columns=df.columns)


  return train_df, test_df

In [71]:
def preproc(train_df, test_df):
    film_columns = ["item_id", "movie title", "release date", "video release date",
              "IMDb URL", "unknown", "Action", "Adventure", "Animation",
              "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
              "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi",
              "Thriller", "War", "Western"]

    films_df = pd.read_csv("./ml-100k/u.item", sep="|", names=film_columns, encoding='latin-1')
    films_df.drop(["movie title", "release date", "IMDb URL", "unknown", "video release date"], axis = 1, inplace = True)

    train_df = pd.merge(train_df, films_df, how='left', left_on='item_id', right_on='item_id')
    test_df = pd.merge(test_df, films_df, how='left', left_on='item_id', right_on='item_id')

    user_columns = ["user_id", "age", "sex", "occupation", "zip_code"]
    user_df = pd.read_csv("./ml-100k/u.user", sep="|", names=user_columns, encoding='latin-1')
    user_df["sex"] = pp.LabelEncoder().fit_transform(user_df["sex"])
    occup_df = pd.read_csv("./ml-100k/u.occupation", sep="\t", names=["jobs"])
    le = pp.LabelEncoder()
    le.fit(occup_df["jobs"])
    user_df["occupation"] = le.transform(user_df["occupation"])
    user_df.drop(["zip_code"], axis = 1, inplace = True)

    train_df = pd.merge(train_df, user_df, how='left', left_on='user_id', right_on='user_id')
    test_df = pd.merge(test_df, user_df, how='left', left_on='user_id', right_on='user_id')
    
    
    train_df["rating"]  = train_df["rating"] - 1
    train_df["age"] = train_df["age"] / user_df["age"].abs().max()
    
    encoder = pp.OneHotEncoder(sparse_output=False)
    encoder.fit(train_df[["occupation"]])
    new_feat = encoder.transform(train_df[["occupation"]])
    new_cols = pd.DataFrame(new_feat, columns=encoder.get_feature_names_out(["occupation"]))
    train_df = pd.concat([train_df, new_cols], axis=1)    
    train_df.drop("occupation", axis=1, inplace=True)
    
    new_feat = encoder.transform(test_df[["occupation"]])
    new_cols = pd.DataFrame(new_feat, columns=encoder.get_feature_names_out(["occupation"]))
    test_df = pd.concat([test_df, new_cols], axis=1)    
    test_df.drop("occupation", axis=1, inplace=True)
    
    test_df["rating"]  = test_df["rating"] - 1
    test_df["age"] = test_df["age"] / user_df["age"].abs().max()

    train_df.drop(["item_id", "user_id", "timestamp"], axis = 1, inplace = True)
    train_y = train_df["rating"].values
    train_x = train_df.drop('rating', axis=1).values

    test_df.drop(["item_id", "user_id", "timestamp"], axis = 1, inplace = True)
    test_y = test_df["rating"].values
    test_x = test_df.drop('rating', axis=1).values
    
#     return train_df, test_df

    return train_x, train_y, test_x, test_y


In [73]:
train_df, test_df = make_dfs()
train_x, train_y, test_x, test_y = preproc(train_df, test_df)

/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [74]:
class LensDataset(torch.utils.data.Dataset):
    def __init__(self, x, y):
      self.x = x
      self.y = y

    def __getitem__(self, index):
      features = self.x[index]
      rating = self.y[index]

      features = torch.tensor(features, dtype=torch.float32)
      rating = torch.tensor(rating, dtype=torch.int64)
      return (features, rating)

    def __len__(self):
        return len(self.y)

In [75]:
train_dataset = LensDataset(train_x, train_y)
test_dataset = LensDataset(test_x, test_y)

In [76]:
batch_size = 128

train_loader = torch.utils.data.DataLoader(train_dataset,
                                           batch_size=batch_size, shuffle=True)

test_loader = torch.utils.data.DataLoader(test_dataset,
                                         batch_size=batch_size, shuffle=False)
loaders = {
    'train' : train_loader,

    'test'  : test_loader,
}

batch = next(iter(train_loader))

print(batch[0].shape, batch[1].shape) # Example of data shapes

tensor([1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000,
        0.2603, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 1.0000, 0.0000, 0.0000]) torch.Size([128])


In [77]:
class Net(nn.Module):
    def __init__(self, inp_size, out_size):
        super(Net, self).__init__()

        self.linear_layers = nn. Sequential(
            nn.Linear(inp_size, 1024, bias=True),
            nn.ReLU(),
            nn.Linear(1024, 4096, bias=True),
            nn.ReLU(),
            nn.Linear(4096, 8192, bias=True),
            nn.ReLU(),
            nn.Linear(8192, 4096, bias=True),
            nn.ReLU(),
            nn.Linear(4096, 256, bias=True),
            nn.ReLU(),
            nn.Linear(256, out_size, bias=True),
            nn.Softmax(),
        )


    def forward(self, x):
        out = self.linear_layers(x)
        return out

In [81]:
from torch.optim import lr_scheduler
import copy
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

inp_size = 41
out_size=5
num_epochs = 40

model = Net(inp_size, out_size).to(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr = 0.00005)

best_model_wts = copy.deepcopy(model.state_dict()) # Best weights
best_loss = 10**10

model

Net(
  (linear_layers): Sequential(
    (0): Linear(in_features=41, out_features=1024, bias=True)
    (1): ReLU()
    (2): Linear(in_features=1024, out_features=4096, bias=True)
    (3): ReLU()
    (4): Linear(in_features=4096, out_features=8192, bias=True)
    (5): ReLU()
    (6): Linear(in_features=8192, out_features=4096, bias=True)
    (7): ReLU()
    (8): Linear(in_features=4096, out_features=256, bias=True)
    (9): ReLU()
    (10): Linear(in_features=256, out_features=5, bias=True)
    (11): Softmax(dim=None)
  )
)

In [82]:
from time import time
from tqdm import tqdm
# Train and test functions
def train(model, device, criterion, optimizer, epoch):
    model.train()
    epoch_loss = 0
    start_time = time()
    correct = 0
    iteration = 0

    bar = tqdm(loaders['train'])
    for data, target in bar:
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()

        output = model(data)
#         print(output)
        loss = criterion(output, target)
        
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
        iteration += 1
        bar.set_postfix({"Loss": format(epoch_loss/iteration, '.6f')})

    print(f'Train Epoch: {epoch}, elapsed time:{time()-start_time:.2f}s, Avg train Loss: {epoch_loss/iteration}')
    return epoch_loss / iteration


def test(model, device, criterion):
    model.eval()
    test_loss = 0
    correct = 0
    total = 0
    iters = 0
    with torch.no_grad():
        for data, target in loaders['test']:
            iters += 1
            data, target = data.to(device), target.to(device)
            output = model(data)
            pred = torch.argmax(output, dim=1)
            if correct == 0:
                print(pred, target)
            correct += sum(pred.eq(target))
            total += len(pred)
            test_loss += criterion(output, target).item()  # sum up batch loss

    test_loss /= iters
    print(f'Avg test Loss: {test_loss}, Avg Accuracy: {correct/total}')
    return test_loss

In [83]:
for _ in range(num_epochs):
    train_loss = train(model, device, criterion, optimizer, _)
    test_loss = test(model, device, criterion)

    if test_loss < best_loss: # Keep the best weights
        best_loss = test_loss
        best_model_wts = copy.deepcopy(model.state_dict())

  0%|          | 0/708 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/modules/container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 708/708 [00:28<00:00, 24.56it/s, Loss=1.525078]


Train Epoch: 0, elapsed time:28.83s, Avg train Loss: 1.5250783025544916
tensor([3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 4, 2, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 3,
        2, 3, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 4,
        3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 4, 3, 2, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5180680977331626, Avg Accuracy: 0.3492046594619751


100%|██████████| 708/708 [00:28<00:00, 24.57it/s, Loss=1.515797]


Train Epoch: 1, elapsed time:28.81s, Avg train Loss: 1.5157972774599906
tensor([3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 4, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, 2, 3,
        2, 3, 2, 2, 3, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 3, 4,
        2, 3, 3, 2, 2, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 4, 2, 2, 4, 3,
        3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5137723426561098, Avg Accuracy: 0.35079532861709595


100%|██████████| 708/708 [00:28<00:00, 24.61it/s, Loss=1.511222]


Train Epoch: 2, elapsed time:28.77s, Avg train Loss: 1.5112220052271912
tensor([3, 3, 3, 2, 3, 3, 3, 4, 3, 2, 2, 4, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, 2, 3,
        2, 3, 2, 2, 3, 3, 4, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 2, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 3, 4, 4,
        2, 4, 3, 2, 2, 4, 3, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3,
        3, 4, 3, 4, 3, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 3, 3, 3, 4, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 4], device='cuda:0')
Avg test Loss: 1.5117452482919436, Avg Accuracy: 0.3529162108898163


100%|██████████| 708/708 [00:28<00:00, 24.61it/s, Loss=1.508713]


Train Epoch: 3, elapsed time:28.78s, Avg train Loss: 1.5087130810581357
tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 2, 3, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3,
        2, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 3, 4,
        3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 2, 2, 3, 2, 2, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 4, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5104575253821708, Avg Accuracy: 0.3582184314727783


100%|██████████| 708/708 [00:28<00:00, 24.61it/s, Loss=1.505978]


Train Epoch: 4, elapsed time:28.78s, Avg train Loss: 1.5059780446486284
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 2, 2, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 2, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 4,
        2, 4, 3, 2, 2, 4, 2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 4, 2, 2, 4, 3,
        3, 3, 3, 3, 3, 3, 3, 4], device='cuda:0')
Avg test Loss: 1.5110001080744975, Avg Accuracy: 0.3549310564994812


100%|██████████| 708/708 [00:28<00:00, 24.55it/s, Loss=1.503991]


Train Epoch: 5, elapsed time:28.85s, Avg train Loss: 1.5039909700889371
tensor([3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 2, 4, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 4,
        2, 4, 3, 2, 2, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3,
        3, 4, 3, 4, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 3, 4, 3, 4, 2, 2, 4, 3,
        3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5089912946159776, Avg Accuracy: 0.36489924788475037


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.501919]


Train Epoch: 6, elapsed time:28.81s, Avg train Loss: 1.5019188562018724
tensor([3, 3, 3, 2, 3, 3, 3, 4, 3, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 2, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 4, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 4,
        2, 4, 3, 2, 2, 4, 2, 2, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 4, 3, 3,
        3, 4, 3, 4, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 3, 4, 3, 4, 2, 2, 4, 3,
        3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5085331990912154, Avg Accuracy: 0.36299043893814087


100%|██████████| 708/708 [00:28<00:00, 24.57it/s, Loss=1.498842]


Train Epoch: 7, elapsed time:28.82s, Avg train Loss: 1.498841812718386
tensor([3, 3, 3, 2, 2, 3, 3, 3, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 3,
        2, 3, 3, 2, 2, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 3, 3, 3, 3, 2, 2, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5143085863139178, Avg Accuracy: 0.35768821835517883


100%|██████████| 708/708 [00:28<00:00, 24.54it/s, Loss=1.495024]


Train Epoch: 8, elapsed time:28.86s, Avg train Loss: 1.4950241793346943
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 3, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 4, 2, 2, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 4,
        2, 4, 3, 2, 2, 4, 2, 2, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 3, 3, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5109197046305682, Avg Accuracy: 0.3573700785636902


100%|██████████| 708/708 [00:28<00:00, 24.62it/s, Loss=1.492170]


Train Epoch: 9, elapsed time:28.76s, Avg train Loss: 1.4921699509782307
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 3, 2, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 4,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 3, 4, 3, 3, 2, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5105859540604256, Avg Accuracy: 0.36362671852111816


100%|██████████| 708/708 [00:28<00:00, 24.59it/s, Loss=1.490611]


Train Epoch: 10, elapsed time:28.80s, Avg train Loss: 1.490610803082838
tensor([3, 3, 3, 2, 2, 3, 3, 4, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 2, 4, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 4,
        2, 4, 3, 2, 2, 4, 2, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 3, 2, 2, 4, 3, 2, 3, 3, 2, 2, 3, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5092847605009336, Avg Accuracy: 0.3632025420665741


100%|██████████| 708/708 [00:28<00:00, 24.56it/s, Loss=1.488860]


Train Epoch: 11, elapsed time:28.83s, Avg train Loss: 1.4888598954273482
tensor([3, 3, 3, 2, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 4,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 3, 4, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5099686013685691, Avg Accuracy: 0.36224812269210815


100%|██████████| 708/708 [00:28<00:00, 24.56it/s, Loss=1.487229]


Train Epoch: 12, elapsed time:28.83s, Avg train Loss: 1.4872292450255593
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 2, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 3, 2, 2, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        2, 4, 3, 2, 2, 3, 2, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 2, 3, 4, 3, 3, 2, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5107568856832143, Avg Accuracy: 0.36352068185806274


100%|██████████| 708/708 [00:28<00:00, 24.53it/s, Loss=1.485339]


Train Epoch: 13, elapsed time:28.86s, Avg train Loss: 1.485339251278484
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 4,
        3, 4, 2, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 4, 4, 3, 4, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5123884645668235, Avg Accuracy: 0.36277836561203003


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.483944]


Train Epoch: 14, elapsed time:28.81s, Avg train Loss: 1.4839440013392498
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 4,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 3, 4, 2, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5115311951250643, Avg Accuracy: 0.3611876964569092


100%|██████████| 708/708 [00:28<00:00, 24.56it/s, Loss=1.482522]


Train Epoch: 15, elapsed time:28.83s, Avg train Loss: 1.4825219232483773
tensor([3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 3, 2, 2, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5107176980456791, Avg Accuracy: 0.3611876964569092


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.480861]


Train Epoch: 16, elapsed time:28.80s, Avg train Loss: 1.4808609300414048
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        2, 4, 3, 2, 2, 4, 2, 2, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 4, 4, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5147130666552364, Avg Accuracy: 0.3554612696170807


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.479255]


Train Epoch: 17, elapsed time:28.81s, Avg train Loss: 1.4792553878436654
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        2, 2, 3, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 3, 2, 4, 3, 3, 3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 3, 4,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 2, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 4, 4, 4, 4, 2, 2, 4, 3,
        3, 3, 2, 2, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5172318961169269, Avg Accuracy: 0.3556733727455139


100%|██████████| 708/708 [00:28<00:00, 24.57it/s, Loss=1.478368]


Train Epoch: 18, elapsed time:28.82s, Avg train Loss: 1.4783683355245214
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 2, 2, 2, 2,
        2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 2, 3, 4, 4, 3, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.511913700683697, Avg Accuracy: 0.3644750714302063


100%|██████████| 708/708 [00:28<00:00, 24.57it/s, Loss=1.476786]


Train Epoch: 19, elapsed time:28.82s, Avg train Loss: 1.4767864873517031
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3,
        3, 4, 3, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 4, 3, 2, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5139776903229791, Avg Accuracy: 0.356097549200058


100%|██████████| 708/708 [00:28<00:00, 24.57it/s, Loss=1.475511]


Train Epoch: 20, elapsed time:28.82s, Avg train Loss: 1.475511453751117
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 3, 2, 2, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5114982724189758, Avg Accuracy: 0.36479321122169495


100%|██████████| 708/708 [00:28<00:00, 24.60it/s, Loss=1.474955]


Train Epoch: 21, elapsed time:28.78s, Avg train Loss: 1.474954563177238
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 2, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 3,
        2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 4, 2, 3, 3, 2, 3, 2, 3, 3,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5123889542914726, Avg Accuracy: 0.36670199036598206


100%|██████████| 708/708 [00:28<00:00, 24.57it/s, Loss=1.473046]


Train Epoch: 22, elapsed time:28.82s, Avg train Loss: 1.473046164054655
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 3, 3, 4, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 3, 4, 4, 4, 3, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5134671926498413, Avg Accuracy: 0.35959702730178833


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.471728]


Train Epoch: 23, elapsed time:28.81s, Avg train Loss: 1.4717277665596225
tensor([3, 3, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 3, 3, 4, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 2, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5139352292627901, Avg Accuracy: 0.363838791847229


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.471290]


Train Epoch: 24, elapsed time:28.80s, Avg train Loss: 1.4712903102238972
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 2, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 3, 3, 4, 3, 3, 3, 3, 3, 4, 2, 3, 3, 3, 3, 2, 3, 3,
        3, 3, 2, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 2, 3, 4, 4, 3, 2, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.51320944122366, Avg Accuracy: 0.36277836561203003


100%|██████████| 708/708 [00:28<00:00, 24.59it/s, Loss=1.470077]


Train Epoch: 25, elapsed time:28.80s, Avg train Loss: 1.4700765956593098
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        3, 3, 3, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 3, 3, 4, 3, 3, 3, 2, 2, 4, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5152061919908266, Avg Accuracy: 0.3607635200023651


100%|██████████| 708/708 [00:28<00:00, 24.62it/s, Loss=1.468801]


Train Epoch: 26, elapsed time:28.76s, Avg train Loss: 1.4688005287431727
tensor([3, 2, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        3, 3, 2, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 3, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 2, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 3,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 3, 4, 4, 2, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5136883742100484, Avg Accuracy: 0.36532342433929443


100%|██████████| 708/708 [00:28<00:00, 24.62it/s, Loss=1.467291]


Train Epoch: 27, elapsed time:28.76s, Avg train Loss: 1.467290933522801
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 2, 3, 2, 4, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 4, 3, 2, 3, 2, 3, 2, 3, 3, 3, 4, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 3, 3, 4, 3, 4, 3, 2, 2, 4, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 2, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.515273648339349, Avg Accuracy: 0.35959702730178833


100%|██████████| 708/708 [00:28<00:00, 24.61it/s, Loss=1.466240]


Train Epoch: 28, elapsed time:28.77s, Avg train Loss: 1.466240193547502
tensor([3, 3, 3, 2, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        3, 3, 3, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 4, 2, 2, 3, 2, 2, 2, 3, 4,
        3, 4, 2, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 4, 4, 4, 4, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5158334100568616, Avg Accuracy: 0.3633085787296295


100%|██████████| 708/708 [00:28<00:00, 24.62it/s, Loss=1.465449]


Train Epoch: 29, elapsed time:28.76s, Avg train Loss: 1.465448883967211
tensor([3, 3, 3, 3, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 3, 4, 4, 2, 3, 4, 3, 3, 2, 3, 3,
        3, 3, 3, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 3, 3, 2, 2, 3, 2, 2, 4, 3, 2, 3, 3, 3, 2, 3, 4, 4, 2, 3, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5136589150171023, Avg Accuracy: 0.3632025420665741


100%|██████████| 708/708 [00:28<00:00, 24.59it/s, Loss=1.464661]


Train Epoch: 30, elapsed time:28.80s, Avg train Loss: 1.4646610157974695
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 4, 2, 3, 3, 2, 2, 2, 3, 3,
        3, 3, 3, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 3, 4, 3, 2, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5153330306749087, Avg Accuracy: 0.3600212037563324


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.463485]


Train Epoch: 31, elapsed time:28.80s, Avg train Loss: 1.4634852183740692
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 3, 2, 2, 2, 4, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 2, 3, 2, 2, 3, 4, 3, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 4, 2, 2, 4, 2, 2, 2, 3, 3,
        3, 3, 2, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 2, 3, 4, 3, 2, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.518734308513435, Avg Accuracy: 0.353658527135849


100%|██████████| 708/708 [00:28<00:00, 24.63it/s, Loss=1.462747]


Train Epoch: 32, elapsed time:28.74s, Avg train Loss: 1.46274748259345
tensor([3, 3, 3, 2, 2, 3, 3, 4, 3, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 4, 2, 3, 3, 2, 3, 2, 3, 3,
        3, 3, 3, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 3, 2, 3, 2, 3, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5152579755396456, Avg Accuracy: 0.3618239462375641


100%|██████████| 708/708 [00:28<00:00, 24.63it/s, Loss=1.462132]


Train Epoch: 33, elapsed time:28.75s, Avg train Loss: 1.462131995602516
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 2, 2, 2, 4, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 4, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 4, 2, 3, 3, 2, 2, 2, 3, 3,
        2, 3, 2, 2, 2, 4, 2, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 3, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 3, 4, 4, 3, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5170081789429124, Avg Accuracy: 0.35662776231765747


100%|██████████| 708/708 [00:28<00:00, 24.60it/s, Loss=1.460674]


Train Epoch: 34, elapsed time:28.78s, Avg train Loss: 1.460674015647274
tensor([3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 2, 3, 2, 4, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 3, 4, 4, 2, 3, 4, 3, 3, 2, 3, 3,
        3, 3, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 2, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 4, 2, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5164871264148403, Avg Accuracy: 0.3615058362483978


100%|██████████| 708/708 [00:28<00:00, 24.58it/s, Loss=1.460413]


Train Epoch: 35, elapsed time:28.81s, Avg train Loss: 1.4604131574347867
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 3, 2, 2, 2, 4, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 4, 4, 2, 3, 4, 2, 2, 2, 3, 3,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
        3, 3, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 3, 4, 4, 2, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.517524326169813, Avg Accuracy: 0.3611876964569092


100%|██████████| 708/708 [00:28<00:00, 24.62it/s, Loss=1.459146]


Train Epoch: 36, elapsed time:28.76s, Avg train Loss: 1.4591464029867096
tensor([3, 3, 3, 2, 2, 3, 3, 4, 3, 3, 2, 3, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 2, 4, 2, 2, 3, 2, 2, 2, 3, 3,
        3, 4, 3, 2, 2, 4, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 3, 2, 3, 4, 3, 2, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5157048009537362, Avg Accuracy: 0.3593849241733551


100%|██████████| 708/708 [00:28<00:00, 24.60it/s, Loss=1.458684]


Train Epoch: 37, elapsed time:28.78s, Avg train Loss: 1.4586843184832126
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 3, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        3, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 4, 2, 2, 2, 2,
        2, 3, 2, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 3, 4, 4, 2, 3, 4, 3, 3, 2, 3, 3,
        3, 3, 3, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 3, 2, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5157281031479706, Avg Accuracy: 0.3633085787296295


100%|██████████| 708/708 [00:28<00:00, 24.55it/s, Loss=1.457768]


Train Epoch: 38, elapsed time:28.84s, Avg train Loss: 1.457768476615518
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2,
        3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 4, 2, 2, 3, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 4, 4, 2, 3, 3, 2, 3, 2, 3, 3,
        3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 3, 4, 3, 2, 2, 2, 2, 2, 4, 3, 2, 2, 3, 2, 3, 3, 4, 4, 2, 3, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5165064850369014, Avg Accuracy: 0.363838791847229


100%|██████████| 708/708 [00:28<00:00, 24.59it/s, Loss=1.456863]


Train Epoch: 39, elapsed time:28.79s, Avg train Loss: 1.4568627666955614
tensor([3, 3, 3, 2, 2, 3, 3, 4, 2, 2, 2, 3, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
        2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2,
        2, 3, 3, 2, 4, 3, 2, 4, 3, 4, 3, 3, 3, 2, 4, 4, 2, 3, 4, 2, 3, 2, 3, 3,
        2, 4, 2, 2, 2, 3, 2, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3,
        3, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 3, 4, 3, 2, 2, 2, 4, 3,
        3, 3, 2, 3, 3, 3, 3, 3], device='cuda:0')
Avg test Loss: 1.5184849355671857, Avg Accuracy: 0.3556733727455139
